# azure-pipelines.yml

# 👇 Event to trigger pipeline execution
trigger:
  branches:
    include:
      - main
      - develop
    # exclude:
    #  - develop # 👈 Excludes the develop branch

# 👇 Configures pipeline execution on pull requests
pr:
  branches:
    include:
      - main # 👈 Filters the execution to run only on the pull requests for the main branch
      - develop
    # exclude:
    #  - develop # 👈 Excludes the pull requests for the develop branch

# Other configurations

# Pipeline stages
stages:
  - stage: Test
    displayName:
      Chromatic Testing
      # Job list
    jobs:
      - job: Chromatic_Deploy_1
        displayName: 'Run Chromatic'
        steps:
          # Other steps in the pipeline
          - checkout: self
            submodules: true
            persistCredentials: true
            displayName: 'Get full Git history'
            fetchDepth: 0

          # 👇 Installs and configures Node environment
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          - task: Cache@2
            displayName: Install and cache packages
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
          - script: npm ci
            condition: ne(variables.CACHE_RESTORED, 'true')

          # 👇 Adds Chromatic as a step in the pipeline
          - task: CmdLine@2
            displayName: 'Run Chromatic'
            inputs:
              #👇Runs Chromatic with the flag to prevent pipeline failure
              script: npx chromatic --auto-accept-changes --build-script-name storybook:build:lit
            env:
              CHROMATIC_PROJECT_TOKEN: $(CHROMATIC_PROJECT_TOKEN_1)
      - job: Chromatic_Deploy_2
        displayName: 'Run Chromatic'
        steps:
          # Other steps in the pipeline
          - checkout: self
            submodules: true
            persistCredentials: true
            displayName: 'Get full Git history'
            fetchDepth: 0

          # 👇 Installs and configures Node environment
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          - task: Cache@2
            displayName: Install and cache packages
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
          - script: npm ci
            condition: ne(variables.CACHE_RESTORED, 'true')

          # 👇 Adds Chromatic as a step in the pipeline
          - task: CmdLine@2
            displayName: 'Run Chromatic'
            inputs:
              #👇Runs Chromatic with the flag to prevent pipeline failure
              script: npx chromatic --auto-accept-changes --build-script-name storybook:build:react
            env:
              CHROMATIC_PROJECT_TOKEN: $(CHROMATIC_PROJECT_TOKEN_2)
